# Generated by Django 5.0.2 on 2024-02-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='phone_number'),
        ),
    ]
