# Generated by Django 5.0.2 on 2024-02-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
