# Generated by Django 5.0.2 on 2024-02-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_video_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='20240214092719', max_length=150),
        ),
    ]
