# Generated by Django 5.0.2 on 2024-02-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_video_video_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='name',
        ),
    ]
