# Generated by Django 5.0.2 on 2024-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
