# Generated by Django 5.0.2 on 2024-02-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('book_file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
