# Generated by Django 5.0.2 on 2024-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True)),
                ('op1', models.CharField(max_length=300, null=True)),
                ('op2', models.CharField(max_length=300, null=True)),
                ('op3', models.CharField(max_length=300, null=True)),
                ('op4', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
