# Generated by Django 5.0.2 on 2024-02-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_quesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
