# Generated by Django 5.0.2 on 2024-03-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_question_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
